import React, { useState } from "react";
import { Link } from "react-router-dom";
import { CheckCircle2, ExternalLink, FileCheck2, Gavel, Link2, Loader2, MessageSquare, Send, ShieldAlert, Users } from "lucide-react";
import { base44 } from "@/api/base44Client";
import { disputeReasonLabel } from "@/lib/matchDisputes";

const fieldClass = "w-full rounded-xl border border-white/10 bg-[#101722] px-3 py-2.5 text-sm text-white outline-none placeholder:text-slate-500 focus:border-cyan/40";
const safeProof = (url) => { try { return ["https:", "http:"].includes(new URL(url).protocol); } catch { return false; } };
const stamp = (value) => value ? new Date(value).toLocaleString() : "";

export default function DisputeReviewCard({ dispute, ticket, onRefresh }) {
  const [reply, setReply] = useState("");
  const [notes, setNotes] = useState("");
  const [target, setTarget] = useState(dispute.reported_against || "");
  const [duration, setDuration] = useState("24h");
  const [confirmBan, setConfirmBan] = useState(false);
  const [busy, setBusy] = useState("");
  const [error, setError] = useState("");
  const [notice, setNotice] = useState("");
  const match = dispute.wager_details || ticket?.match_details || {};
  const roster = dispute.match_roster || ticket?.match_roster || [];
  const closed = ["resolved", "rejected", "closed"].includes(dispute.status);
  const proof = [...new Set([...(dispute.submitted_evidence || []), ...(dispute.evidence_urls || []), ...(dispute.screenshots || []), ...(dispute.videos || []), ...(dispute.additional_evidence_urls || [])])].filter((url) => typeof url === "string" && safeProof(url));
  const messages = (ticket?.messages || []).filter((message) => !message.internal);
  const submissions = dispute.submissions?.length ? dispute.submissions : [{ description: dispute.description, reason: dispute.reason, reported_by_name: dispute.reported_by_name, reported_against_name: dispute.reported_against_name }];
  const matchPath = ["8s", "money8s"].includes(dispute.match_type || match.match_type) ? `/8s-match/${dispute.match_id || dispute.wager_id}`
    : dispute.match_type === "ranked" ? `/ranked-match/${dispute.match_id}` : dispute.match_type === "xp" ? `/xp-match/${dispute.match_id}`
      : dispute.match_type === "tournament" ? `/tournament-match/${dispute.match_id}` : `/wagers-match/${dispute.match_id || dispute.wager_id}`;
  const invoke = async (name, payload, label) => {
    setBusy(payload.action || name); setError(""); setNotice("");
    try {
      const response = await base44.functions.invoke(name, payload);
      if (!response.data?.success) throw new Error(response.data?.error || "Could not update dispute.");
      setNotice(label); await onRefresh(); return true;
    } catch (failure) { setError(failure.message); return false; }
    finally { setBusy(""); }
  };
  const act = async (action) => {
    if (action !== "review_proof" && !notes.trim()) { setError("Add a decision or moderation reason first."); return; }
    if (action === "ban_player" && (!target || !confirmBan)) { setError("Choose a player and confirm the ban."); return; }
    const ok = await invoke("moderateDispute", { dispute_id: dispute.id, action, notes: notes.trim(), ...(action === "ban_player" ? { user_id: target, duration } : {}) },
      action === "review_proof" ? "Evidence marked as reviewed." : action === "ban_player" ? "Player ban recorded. Resolve the match separately." : "Dispute resolved.");
    if (ok && action === "ban_player") setConfirmBan(false);
  };
  return <article className="space-y-5 bg-[#151d29] px-5 py-5 text-white">
    <header className="flex flex-wrap items-start justify-between gap-3"><div><div className="flex items-center gap-2"><Gavel className="h-5 w-5 text-orange" /><h3 className="text-base font-black">{disputeReasonLabel(dispute.reason)}</h3><span className={`rounded-full border px-2.5 py-1 text-[10px] font-bold ${closed ? "border-green/25 text-green" : "border-orange/25 text-orange"}`}>{String(dispute.status || "pending").replaceAll("_", " ")}</span></div><p className="mt-2 text-xs text-slate-400">Case #{dispute.id.slice(-8)} · {dispute.reported_by_name || dispute.reported_by} · {stamp(dispute.created_date)}</p><p className="mt-1 text-xs text-slate-400">Reported: <strong className="text-white">{dispute.reported_against_name || "General match issue"}</strong> · Priority: {dispute.priority || "medium"}</p></div><Link to={matchPath} className="inline-flex items-center gap-2 rounded-xl border border-cyan/20 bg-cyan/10 px-4 py-2.5 text-xs font-bold text-cyan">Open match room <ExternalLink className="h-3.5 w-3.5" /></Link></header>
    <div className="grid gap-4 xl:grid-cols-2"><div className="space-y-4"><section className="rounded-xl border border-white/[0.08] bg-black/10 p-4"><h4 className="mb-3 text-xs font-bold text-slate-300">Reports</h4><div className="space-y-3">{submissions.map((submission, index) => <div key={index} className="rounded-lg bg-white/[0.025] p-3"><p className="text-[10px] font-bold text-orange">{disputeReasonLabel(submission.reason)} · {submission.reported_by_name || dispute.reported_by_name}{submission.reported_against_name ? ` → ${submission.reported_against_name}` : ""}</p><p className="mt-2 whitespace-pre-wrap break-words text-sm leading-6 text-slate-200">{submission.description || "No description attached."}</p></div>)}</div></section>
      <section className="rounded-xl border border-white/[0.08] bg-black/10 p-4"><h4 className="flex items-center gap-2 text-xs font-bold"><Link2 className="h-4 w-4 text-cyan" /> Evidence</h4><div className="mt-3 space-y-2">{proof.length ? proof.map((url, index) => <a key={url} href={url} target="_blank" rel="noopener noreferrer" className="flex items-center gap-2 rounded-lg border border-cyan/10 bg-cyan/5 p-3 text-xs text-cyan"><span className="shrink-0 font-bold">Proof {index + 1}</span><span className="min-w-0 flex-1 truncate">{url}</span><ExternalLink className="h-3.5 w-3.5 shrink-0" /></a>) : <p className="text-xs text-slate-400">No evidence links attached. Ask for proof in the conversation.</p>}</div>{dispute.proof_reviewed_date && <p className="mt-3 flex items-center gap-2 text-[10px] text-green"><FileCheck2 className="h-3.5 w-3.5" /> Reviewed by {dispute.proof_reviewed_by_name} · {stamp(dispute.proof_reviewed_date)}</p>}{!closed && <button disabled={!!busy} onClick={() => act("review_proof")} className="mt-3 rounded-lg border border-white/10 px-3 py-2 text-xs font-bold text-slate-200 disabled:opacity-50">Mark evidence reviewed</button>}</section>
      <section className="rounded-xl border border-white/[0.08] bg-black/10 p-4"><h4 className="flex items-center gap-2 text-xs font-bold"><MessageSquare className="h-4 w-4 text-cyan" /> Conversation with players</h4><div className="mt-3 max-h-52 space-y-2 overflow-y-auto">{messages.length ? messages.map((message, index) => <div key={message.id || index} className="rounded-lg bg-white/[0.025] p-3"><p className="text-[10px] text-slate-400">{message.sender_name} · {stamp(message.created_date)}</p><p className="mt-1 whitespace-pre-wrap break-words text-sm text-slate-200">{message.content}</p></div>) : <p className="text-xs text-slate-400">No replies yet.</p>}</div>{ticket && !closed && <div className="mt-3 space-y-2"><textarea aria-label="Reply to players" value={reply} onChange={(event) => setReply(event.target.value)} rows={3} className={fieldClass} placeholder="Ask for a clip, explain the review, or reply to the players…" /><button disabled={!!busy || !reply.trim()} onClick={async () => { if (await invoke("replyTicket", { ticket_id: ticket.id, message: reply.trim() }, "Reply sent to players.")) setReply(""); }} className="inline-flex items-center gap-2 rounded-lg bg-cyan px-4 py-2.5 text-xs font-black text-background disabled:opacity-50"><Send className="h-3.5 w-3.5" /> Send reply</button></div>}{!ticket && <p className="mt-3 text-xs text-orange">No conversation ticket linked to this legacy dispute.</p>}</section></div>
      <div className="space-y-4"><section className="rounded-xl border border-white/[0.08] bg-black/10 p-4"><h4 className="text-xs font-bold">Match context</h4><p className="mt-3 text-sm font-bold">{match.game_mode_display || match.game_mode || "Match"} · {match.team_size || "4v4"} · BO{match.best_of || 1}</p><p className="mt-1 text-xs text-slate-400">#{String(dispute.match_id || dispute.wager_id || "").slice(-8)} · {String(match.status || "unknown").replaceAll("_", " ")}</p><p className="mt-3 text-xs text-slate-400">{match.host_name || "Team Alpha"} vs {match.challenger_name || "Team Bravo"}</p><p className="mt-2 text-xs text-slate-400">Maps: {(match.series_maps || []).map((map) => typeof map === "string" ? map : map.map_name || map.name).filter(Boolean).join(" · ") || match.final_map_name || "Pending"}</p><p className="mt-2 text-xs text-slate-400">Reported score: {match.host_reported_score_alpha ?? match.confirmed_score_alpha ?? "—"} – {match.host_reported_score_bravo ?? match.confirmed_score_bravo ?? "—"}</p></section>
      <section className="rounded-xl border border-white/[0.08] bg-black/10 p-4"><h4 className="mb-3 flex items-center gap-2 text-xs font-bold"><Users className="h-4 w-4 text-orange" /> Players & Activision IDs</h4><div className="space-y-2">{roster.map((player) => <div key={player.user_id} className={`flex items-start justify-between gap-2 rounded-lg p-2.5 ${player.user_id === dispute.reported_against ? "border border-orange/25 bg-orange/5" : "bg-white/[0.025]"}`}><div className="min-w-0"><p className="truncate text-xs font-bold">{player.user_name}{player.is_captain ? " · Captain" : ""}</p><p className="mt-1 break-all text-[10px] text-slate-400">{player.activision_id || "Activision ID not set"}</p></div><span className="shrink-0 text-[10px] text-slate-400">{player.team === "host" ? "Alpha" : "Bravo"}</span></div>)}</div></section>
      <details className="rounded-xl border border-white/[0.08] bg-black/10 p-4"><summary className="cursor-pointer text-xs font-bold">Match chat & history</summary><div className="mt-3 max-h-52 space-y-2 overflow-auto text-xs text-slate-400">{(dispute.chat_logs || []).map((message, index) => <p key={message.id || index} className="whitespace-pre-wrap break-words"><strong className="text-slate-200">{message.sender_name || "Player"}:</strong> {message.content || message.message}</p>)}{(dispute.match_history || []).map((row, index) => <p key={row.id || index}>{row.summary || row.result || row.status || row.id}</p>)}</div></details></div></div>
    {closed ? <div className="rounded-xl border border-green/20 bg-green/5 p-4"><p className="flex items-center gap-2 text-xs font-bold text-green"><CheckCircle2 className="h-4 w-4" /> Resolved by {dispute.resolved_by_name || "Staff"}</p><p className="mt-2 whitespace-pre-wrap text-sm text-slate-300">{dispute.resolution || dispute.decision}</p></div> : <section className="space-y-3 rounded-xl border border-orange/20 bg-orange/[0.025] p-4"><h4 className="text-xs font-bold">Decision & moderation</h4><textarea aria-label="Decision notes" value={notes} onChange={(event) => setNotes(event.target.value)} rows={2} className={fieldClass} placeholder="Record what you reviewed and explain your decision…" /><div className="flex flex-wrap gap-2">{[["resolve_dispute", "Resolve / resume match"], ["approve_team_a", "Award Alpha win"], ["approve_team_b", "Award Bravo win"], ["force_replay", "Force replay"], ["reject_dispute", "Reject report"]].map(([action, label]) => <button key={action} disabled={!!busy} onClick={() => act(action)} className="rounded-lg border border-white/10 bg-white/[0.04] px-3 py-2 text-xs font-bold hover:border-orange/30 disabled:opacity-50">{busy === action ? "Working…" : label}</button>)}</div>
      {!!roster.length && <details className="border-t border-white/[0.08] pt-3"><summary className="flex cursor-pointer items-center gap-2 text-xs font-bold text-red-300"><ShieldAlert className="h-4 w-4" /> Ban a player after review</summary><div className="mt-3 grid gap-3 sm:grid-cols-2"><select aria-label="Player to ban" value={target} onChange={(event) => { setTarget(event.target.value); setConfirmBan(false); }} className={fieldClass}><option value="">Choose player</option>{roster.map((player) => <option key={player.user_id} value={player.user_id}>{player.user_name}</option>)}</select><select aria-label="Ban duration" value={duration} onChange={(event) => { setDuration(event.target.value); setConfirmBan(false); }} className={fieldClass}>{[["24h", "24 hours"], ["3d", "3 days"], ["7d", "7 days"], ["14d", "14 days"], ["30d", "30 days"], ["permanent", "Permanent"]].map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select><label className="flex items-center gap-2 text-xs text-slate-300 sm:col-span-2"><input type="checkbox" checked={confirmBan} onChange={(event) => setConfirmBan(event.target.checked)} /> I reviewed the evidence and confirm this player ban.</label><button disabled={!!busy || !confirmBan || !target} onClick={() => act("ban_player")} className="rounded-lg border border-red-400/25 bg-red-400/10 px-4 py-2.5 text-xs font-bold text-red-300 disabled:opacity-50">Confirm player ban</button></div></details>}
    </section>}
    {!!dispute.review_actions?.length && <p className="text-[10px] text-slate-400">Latest staff action: {dispute.review_actions.at(-1).admin_name} · {String(dispute.review_actions.at(-1).action).replaceAll("_", " ")} · {dispute.review_actions.at(-1).notes}</p>}
    {busy && <p className="flex items-center gap-2 text-xs text-cyan"><Loader2 className="h-3.5 w-3.5 animate-spin" /> Updating case…</p>}{error && <p role="alert" className="rounded-lg border border-red-400/20 bg-red-400/10 p-3 text-xs text-red-300">{error}</p>}{notice && <p role="status" className="text-xs text-green">{notice}</p>}
  </article>;
}
