import { randomInt } from "node:crypto";

export const playerJokes = Object.freeze([
  "aimed at the enemy and somehow hit next Tuesday. 🎯",
  "went 0_o so hard the scoreboard asked if the controller was connected. 🎮",
  "has movement sponsored by the respawn screen. 💀",
  "isn't missing shots — just warning the walls. 🧱",
  "called out ‘one shot’ after doing zero damage. 📢",
  "holds angles so patiently the enemy already started the next match. ⏳",
  "has a minimap, but apparently it's just decoration. 🗺️",
  "is the reason the team has a ‘we go next’ button. 🔄",
  "reloaded with 29 bullets because that last bullet looked suspicious. 🔫",
  "brought a warm-up performance to the grand final. 🏆",
  "plays hide and seek, but the enemy always finds them first. 👀",
  "threw a trophy system and expected an actual trophy. 🏅",
  "has elite movement between the lobby and the respawn screen. 🏃",
  "heard ‘rotate’ and spun around in the spawn. 🌀",
  "is carrying the team... straight back to the lobby. 😂",
  "missed so many shots the enemy sent a thank-you message. 💌",
  "joined ranked while the tutorial was still downloading. 📥",
  "pre-aimed the right corner... on the wrong map. 🗺️",
  "has a long-distance relationship with the crosshair. 🎯",
  "somehow lost a 1v0. The replay is under investigation. 🕵️",
  "called ‘full team mid’ and it was our own team. 📢",
  "rotated to the next hill, but it's on next week's schedule. 📅",
  "finished the map with zero kills and called it a support role. 🤝",
  "planted confidence instead of the bomb. 💣",
  "has a clutch highlight reel that's still buffering. ⏳",
  "challenged a sniper with pure optimism. 🔭",
  "said ‘watch this’ and gave the enemy a highlight clip. 🎬",
  "has more attachments than confirmed hits. 🔧",
  "turned aim assist into aim resistance. 🧲",
  "is undefeated in the warm-up lobby with no opponents. 🏆",
  "slid into the gunfight and straight onto the scoreboard's bottom row. 🛝",
  "heard ‘play your life’ and opened the Settings menu. ⚙️",
  "checked every corner except the one with the enemy in it. 👀",
  "has more time in the killcam than in the actual gunfight. 📺",
  "uses the respawn timer as a personal countdown to another adventure. ⏱️",
  "said ‘I'm frying’ while the scoreboard was still frozen. 🧊",
  "mistook the hardpoint for a sightseeing destination. 📸",
  "saved the streaks for the next tournament. 🚁",
  "threw a smoke and lost their own route home. 🌫️",
  "has perfect recoil control when the gun is empty. 🔫",
  "made a flank so wide it needed a boarding pass. ✈️",
  "went 0_o and blamed the gaming chair's firmware. 🪑",
  "called ‘trade me’ before the round even started. 🔄",
  "is playing objective... the objective is finding the objective. 🧭",
  "holds the bomb like it's a souvenir from spawn. 🎁",
  "won the coin toss and put it in the montage. 🪙",
  "said ‘easy lobby’ and became the easy part. 😂",
  "has a loadout for every situation except hitting the enemy. 🎒",
  "went for the ninja defuse wearing tap-dancing shoes. 🥷",
  "brought championship confidence and practice-range accuracy. 👑",
]);

export function playerJokePayload(userId) {
  return {
    content: `😂 <@${userId}> ${playerJokes[randomInt(playerJokes.length)]}`,
    allowedMentions: { parse: [] },
  };
}
